### ISSUE TITLE
配置好搭建好之后点击登陆没反应 导入sql点击登陆

### ISSUE THREAD

**Issue by DexSinis** [Eliteams/quick4j#3]
subject.login(new UsernamePasswordToken(user.getUsername(), user.getPassword())); 
这里不知道为什么抛出异常

**Comment by qydzchy** [comment]
表示 我的也是一样的情况  登录验证过不了

**Comment by jsnyoung** [comment]
我也是，什么原因？
密码123456

**Comment by chuncanjiaoyu** [comment]
将mysql里面的user的密码改成123456即可
8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92 -> 123456

**Comment by hangkongwei** [comment]
检查js校验文件，GitHub上项目js校验文件不全，网上下载覆盖即可。

**Comment by 674236876** [comment]
原因是登录失败了，shiro的配置中没有加入密码加密配置，但是sql中的密码是加密了的， 在不修改代码的前提下可以直接把数据库的密码修改成123456。 即可登录

**Comment by LifeLongInteresting** [comment]
IE可以登录，chrome不能登录...

**Comment by JinQiangWang2021** [comment]
> 我也是，什么原因？
> 密码123456

实践验证，完美解决
